extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_ttc_textures_05800_rgba16_i8[];
extern Vtx castle_grounds_dl_Sphere_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Sphere_mesh_layer_1_vtx_0[973];
extern Gfx castle_grounds_dl_Sphere_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx castle_grounds_dl_Sphere_mesh_layer_1[];
