#include <ultra64.h>
#include "sm64.h"
#include "behavior_data.h"
#include "model_ids.h"
#include "seq_ids.h"
#include "dialog_ids.h"
#include "segment_symbols.h"
#include "level_commands.h"

#include "game/level_update.h"

#include "levels/scripts.h"

#include "actors/common1.h"

#include "make_const_nonconst.h"
#include "levels/castle_inside/header.h"

static const LevelScript script_func_local_1[] = {
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_GROUNDS_A,  /*destLevel*/ LEVEL_CASTLE_GROUNDS,   /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_GROUNDS_00,          /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_GROUNDS_B,  /*destLevel*/ LEVEL_CASTLE_GROUNDS,   /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_GROUNDS_01,          /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_COURTYARD,         /*destLevel*/ LEVEL_CASTLE_COURTYARD, /*destArea*/ 0x01, /*destNode*/ WARP_COURTYARD_TO_CASTLE_INSIDE, /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_CASTLE_STAR_DOOR_8_STARS, /*pos*/ -2706,   512, -1409, /*angle*/ 0,  45, 0, /*behParam*/ (8 << 24), /*beh*/ bhvStarDoor),
    OBJECT(/*model*/ MODEL_CASTLE_STAR_DOOR_8_STARS, /*pos*/ -2598,   512, -1517, /*angle*/ 0, 225, 0, /*behParam*/ (8 << 24), /*beh*/ bhvStarDoor),
    OBJECT(/*model*/ MODEL_CASTLE_KEY_DOOR,          /*pos*/ -1100,   512, -1074, /*angle*/ 0,   0, 0, /*behParam*/ ((1 << 24) | (WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_2_A << 16)), /*beh*/ bhvDoorWarp),
    OBJECT(/*model*/ MODEL_CASTLE_KEY_DOOR,          /*pos*/  -946,   512, -1074, /*angle*/ 0, 180, 0, /*behParam*/ ((1 << 24) | (WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_2_B << 16)), /*beh*/ bhvDoorWarp),
    OBJECT(/*model*/ MODEL_CASTLE_KEY_DOOR,          /*pos*/ -1100, -1074,   922, /*angle*/ 0,   0, 0, /*behParam*/ ((2 << 24) | (WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_3_A << 16)), /*beh*/ bhvDoorWarp),
    OBJECT(/*model*/ MODEL_CASTLE_KEY_DOOR,          /*pos*/  -946, -1074,   922, /*angle*/ 0, 180, 0, /*behParam*/ ((2 << 24) | (WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_3_B << 16)), /*beh*/ bhvDoorWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_2_A, /*destLevel*/ LEVEL_CASTLE,           /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_TO_CASTLE_INSIDE_1_A, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_2_B, /*destLevel*/ LEVEL_CASTLE,           /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_TO_CASTLE_INSIDE_1_B, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_3_A, /*destLevel*/ LEVEL_CASTLE,           /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_TO_CASTLE_INSIDE_1_A, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_3_B, /*destLevel*/ LEVEL_CASTLE,           /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_TO_CASTLE_INSIDE_1_B, /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/ -5222,   410,   -154, /*angle*/ 0,  90, 0, /*behParam*/ ((PAINTING_ID_CASTLE_BOB << 24) | (WARP_CASTLE_INSIDE_1_PAINTING_BOB << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/ -2611,  -307,  -4352, /*angle*/ 0,   0, 0, /*behParam*/ ((PAINTING_ID_CASTLE_CCM << 24) | (WARP_CASTLE_INSIDE_1_PAINTING_CCM << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/   -51,  -205,  -4506, /*angle*/ 0,   0, 0, /*behParam*/ ((PAINTING_ID_CASTLE_WF  << 24) | (WARP_CASTLE_INSIDE_1_PAINTING_WF  << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/  4300,   410,   -538, /*angle*/ 0, 270, 0, /*behParam*/ ((PAINTING_ID_CASTLE_JRB << 24) | (WARP_CASTLE_INSIDE_1_PAINTING_JRB << 16)), /*beh*/ bhvPainting),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_PAINTING_BOB, /*destLevel*/ LEVEL_BOB,              /*destArea*/ 0x01, /*destNode*/ WARP_BOB_MAIN_ENTRY,             /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_PAINTING_CCM, /*destLevel*/ LEVEL_CCM,              /*destArea*/ 0x01, /*destNode*/ WARP_CCM_1_MAIN_ENTRY,           /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_PAINTING_WF,  /*destLevel*/ LEVEL_WF,               /*destArea*/ 0x01, /*destNode*/ WARP_WF_MAIN_ENTRY,              /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_PAINTING_JRB, /*destLevel*/ LEVEL_JRB,              /*destArea*/ 0x01, /*destNode*/ WARP_JRB_1_MAIN_ENTRY,           /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  2013,  768, -2014, /*angle*/ 0,    0, 0, /*behParam*/               (WARP_CASTLE_INSIDE_1_TO_PSS   << 16),  /*beh*/ bhvWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_PSS,       /*destLevel*/ LEVEL_PSS,              /*destArea*/ 0x01, /*destNode*/ WARP_PSS_MAIN_ENTRY,             /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -5513,  512, -4324, /*angle*/ 0,    0, 0, /*behParam*/ ((48 << 24) | (WARP_CASTLE_INSIDE_1_TO_BITDW << 16)), /*beh*/ bhvWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_BITDW,     /*destLevel*/ LEVEL_BITDW,            /*destArea*/ 0x01, /*destNode*/ WARP_BITDW_MAIN_ENTRY,           /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  1963,  819,  1280, /*angle*/ 0,    0, 0, /*behParam*/ (( 5 << 24) | (WARP_CASTLE_INSIDE_1_TO_SA    << 16)), /*beh*/ bhvWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_TO_SA,        /*destLevel*/ LEVEL_SA,               /*destArea*/ 0x01, /*destNode*/ WARP_SA_MAIN_ENTRY,              /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_NODE_LOOK_UP,                 /*destLevel*/ LEVEL_TOTWC,            /*destArea*/ 0x01, /*destNode*/ WARP_TOTWC_MAIN_ENTRY,           /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1024,  512,  -650, /*angle*/ 0,    0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_1E                    << 16), /*beh*/ bhvInstantActiveWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1024,  -50,   717, /*angle*/ 0,  180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_1F                    << 16), /*beh*/ bhvInstantActiveWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1024,  900,   717, /*angle*/ 0,  180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_SECRET_WARP      << 16), /*beh*/ bhvAirborneWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1024,  900,   717, /*angle*/ 0,  180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_21                    << 16), /*beh*/ bhvAirborneDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1024,  900,   717, /*angle*/ 0,  180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_22                    << 16), /*beh*/ bhvHardAirKnockBackWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1024,  900,   717, /*angle*/ 0,  180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_SECRET_DEATH     << 16), /*beh*/ bhvDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -5513,  512, -4324, /*angle*/ 0, -135, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_BOWSER_1_SUCCESS << 16), /*beh*/ bhvLaunchStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -5513,  512, -4324, /*angle*/ 0, -135, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_BITDW_DEATH      << 16), /*beh*/ bhvLaunchDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1024,  900,   717, /*angle*/ 0,    0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_SECRET_SUCCESS   << 16), /*beh*/ bhvAirborneStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  2816, 1200,  -256, /*angle*/ 0,   90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_SA_SUCCESS       << 16), /*beh*/ bhvAirborneStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  2816, 1200,  -256, /*angle*/ 0,  270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_SA_DEATH         << 16), /*beh*/ bhvDeathWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_1E,                    /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_1E,                    /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_1F,                    /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_1F,                    /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_SECRET_WARP,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_SECRET_WARP,      /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_21,                    /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_21,                    /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_22,                    /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_22,                    /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_SECRET_DEATH,     /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_SECRET_DEATH,     /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_BOWSER_1_SUCCESS, /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_BOWSER_1_SUCCESS, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_BITDW_DEATH,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_BITDW_DEATH,      /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_SECRET_SUCCESS,   /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_SECRET_SUCCESS,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_SA_SUCCESS,       /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_SA_SUCCESS,       /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_SA_DEATH,         /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_SA_DEATH,         /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -5422, 717,  -461, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_BOB_SUCCESS << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -2304,   0, -4552, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_CCM_SUCCESS << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/   256, 102, -4706, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_WF_SUCCESS  << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  4501, 717,  -230, /*angle*/ 0,  90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_JRB_SUCCESS << 16), /*beh*/ bhvPaintingStarCollectWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_BOB_SUCCESS,    /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_BOB_SUCCESS, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_CCM_SUCCESS,    /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_CCM_SUCCESS, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_WF_SUCCESS,     /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_WF_SUCCESS,  /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_JRB_SUCCESS,    /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_JRB_SUCCESS, /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -5422, 717,  -461, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_BOB_DEATH   << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -2304,   0, -4552, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_CCM_DEATH   << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/   256, 102, -4706, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_WF_DEATH    << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  4501, 717,  -230, /*angle*/ 0,  90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_1_FROM_JRB_DEATH   << 16), /*beh*/ bhvPaintingDeathWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_BOB_DEATH,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_BOB_DEATH, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_CCM_DEATH,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_CCM_DEATH, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_WF_DEATH,       /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_WF_DEATH,  /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_1_FROM_JRB_DEATH,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_FROM_JRB_DEATH, /*flags*/ WARP_NO_CHECKPOINT),
    RETURN(),
};

static const LevelScript script_func_local_2[] = {
    OBJECT(/*model*/ MODEL_CASTLE_KEY_DOOR, /*pos*/ -1100, 512, 3021, /*angle*/ 0,   0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_TO_CASTLE_INSIDE_1_A << 16), /*beh*/ bhvDoorWarp),
    OBJECT(/*model*/ MODEL_CASTLE_KEY_DOOR, /*pos*/  -946, 512, 3021, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_TO_CASTLE_INSIDE_1_B << 16), /*beh*/ bhvDoorWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_TO_CASTLE_INSIDE_1_A, /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_2_A, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_TO_CASTLE_INSIDE_1_B, /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_2_B, /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_CASTLE_STAR_DOOR_50_STARS, /*pos*/ -281, 2253, 4762, /*angle*/ 0,   0, 0, /*behParam*/ 0x32000000, /*beh*/ bhvStarDoor),
    OBJECT(/*model*/ MODEL_CASTLE_STAR_DOOR_50_STARS, /*pos*/ -127, 2253, 4762, /*angle*/ 0, 180, 0, /*behParam*/ 0x32000000, /*beh*/ bhvStarDoor),
    OBJECT(/*model*/ MODEL_CASTLE_STAR_DOOR_70_STARS, /*pos*/ -281, 3174, 3772, /*angle*/ 0,   0, 0, /*behParam*/ 0x46000000, /*beh*/ bhvStarDoor),
    OBJECT(/*model*/ MODEL_CASTLE_STAR_DOOR_70_STARS, /*pos*/ -127, 3174, 3772, /*angle*/ 0, 180, 0, /*behParam*/ 0x46000000, /*beh*/ bhvStarDoor),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/  -967,  1306,   -143, /*angle*/   0,   0, 0, /*behParam*/ ((PAINTING_ID_CASTLE_WDW      << 24) | (WARP_CASTLE_INSIDE_2_PAINTING_WDW      << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/ -4599,  1355,   3005, /*angle*/   0, 180, 0, /*behParam*/ ((PAINTING_ID_CASTLE_THI_TINY << 24) | (WARP_CASTLE_INSIDE_2_PAINTING_THI_TINY << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/  -547,  1357,   3813, /*angle*/   0, 180, 0, /*behParam*/ ((PAINTING_ID_CASTLE_TTM      << 24) | (WARP_CASTLE_INSIDE_2_PAINTING_TTM      << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/     0,  2714,   7233, /*angle*/   0, 180, 0, /*behParam*/ ((PAINTING_ID_CASTLE_TTC      << 24) | (WARP_CASTLE_INSIDE_2_PAINTING_TTC      << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/  3180,  1408,   -271, /*angle*/   0,   0, 0, /*behParam*/ ((PAINTING_ID_CASTLE_SL       << 24) | (WARP_CASTLE_INSIDE_2_PAINTING_SL       << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/ -5615,  1510,  -3292, /*angle*/   0,   0, 0, /*behParam*/ ((PAINTING_ID_CASTLE_THI_HUGE << 24) | (WARP_CASTLE_INSIDE_2_PAINTING_THI_HUGE << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/ -3513,  2970,   5989, /*angle*/ 270,   0, 0, /*behParam*/ ((PAINTING_ID_CASTLE_RR       << 24) | (WARP_CASTLE_INSIDE_2_PAINTING_RR       << 16)), /*beh*/ bhvPainting),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_PAINTING_WDW,         /*destLevel*/ LEVEL_WDW,    /*destArea*/ 0x01, /*destNode*/ WARP_WDW_1_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_PAINTING_THI_TINY,    /*destLevel*/ LEVEL_THI,    /*destArea*/ 0x02, /*destNode*/ WARP_THI_2_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_PAINTING_TTM,         /*destLevel*/ LEVEL_TTM,    /*destArea*/ 0x01, /*destNode*/ WARP_TTM_1_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_PAINTING_TTC,         /*destLevel*/ LEVEL_TTC,    /*destArea*/ 0x01, /*destNode*/ WARP_TTC_MAIN_ENTRY,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_PAINTING_SL,          /*destLevel*/ LEVEL_SL,     /*destArea*/ 0x01, /*destNode*/ WARP_SL_1_MAIN_ENTRY,  /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_PAINTING_THI_HUGE,    /*destLevel*/ LEVEL_THI,    /*destArea*/ 0x01, /*destNode*/ WARP_THI_1_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_PAINTING_RR,          /*destLevel*/ LEVEL_RR,     /*destArea*/ 0x01, /*destNode*/ WARP_RR_MAIN_ENTRY,    /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  3002, 2816,  5886, /*angle*/ 0,   0, 0, /*behParam*/ ((15 << 24) | (WARP_CASTLE_INSIDE_2_TO_WMOTR << 16)), /*beh*/ bhvWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_TO_WMOTR,             /*destLevel*/ LEVEL_WMOTR,  /*destArea*/ 0x01, /*destNode*/ WARP_WMOTR_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  -230, 4813, -3352, /*angle*/ 0,   0, 0, /*behParam*/ ((15 << 24) | (WARP_CASTLE_INSIDE_2_TO_BITS  << 16)), /*beh*/ bhvWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_TO_BITS,              /*destLevel*/ LEVEL_BITS,   /*destArea*/ 0x01, /*destNode*/ WARP_BITS_MAIN_ENTRY,  /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  -659, 1613,  -350, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_WDW_SUCCESS   << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -4693, 2157,  1828, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_THI_2_SUCCESS << 16), /*beh*/ bhvAirborneStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  -675, 1400,  3870, /*angle*/ 0,   0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_TTM_SUCCESS   << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  -205, 2918,  7300, /*angle*/ 0,   0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_TTC_SUCCESS   << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  3538, 1766,  -400, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_SL_SUCCESS    << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -4693, 2157,  1828, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_THI_1_SUCCESS << 16), /*beh*/ bhvAirborneStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  3002, 2816,  5886, /*angle*/ 0,  90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_WMOTR_SUCCESS << 16), /*beh*/ bhvLaunchStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -3412, 2816,  5886, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_RR_SUCCESS    << 16), /*beh*/ bhvLaunchStarCollectWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_WDW_SUCCESS,     /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_WDW_SUCCESS,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_THI_2_SUCCESS,   /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_THI_2_SUCCESS, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_TTM_SUCCESS,     /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_TTM_SUCCESS,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_TTC_SUCCESS,     /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_TTC_SUCCESS,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_SL_SUCCESS,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_SL_SUCCESS,    /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_THI_1_SUCCESS,   /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_THI_1_SUCCESS, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_WMOTR_SUCCESS,   /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_WMOTR_SUCCESS, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_RR_SUCCESS,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_RR_SUCCESS,    /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  -659, 1613,  -350, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_WDW_DEATH   << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -4693, 2157,  1828, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_THI_2_DEATH << 16), /*beh*/ bhvDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  -675, 1400,  3870, /*angle*/ 0,   0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_TTM_DEATH   << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  -205, 2918,  7300, /*angle*/ 0,   0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_TTC_DEATH   << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  3538, 1766,  -400, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_SL_DEATH    << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -4693, 2157,  1828, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_THI_1_DEATH << 16), /*beh*/ bhvDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  -230, 4813, -3352, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_BITS_DEATH  << 16), /*beh*/ bhvLaunchDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -3412, 2816,  5886, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_RR_DEATH    << 16), /*beh*/ bhvLaunchDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  3002, 2816,  5886, /*angle*/ 0,  90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_2_FROM_WMOTR_DEATH << 16), /*beh*/ bhvLaunchDeathWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_WDW_DEATH,       /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_WDW_DEATH,    /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_THI_2_DEATH,     /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_THI_2_DEATH,  /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_TTM_DEATH,       /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_TTM_DEATH,    /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_TTC_DEATH,       /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_TTC_DEATH,    /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_SL_DEATH,        /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_SL_DEATH,     /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_THI_1_DEATH,     /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_THI_1_DEATH,  /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_BITS_DEATH,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_BITS_DEATH,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_RR_DEATH,        /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_RR_DEATH,     /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_2_FROM_WMOTR_DEATH,     /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x02, /*destNode*/ WARP_CASTLE_INSIDE_2_FROM_WMOTR_DEATH,  /*flags*/ WARP_NO_CHECKPOINT),
    RETURN(),
};

static const LevelScript script_func_local_3[] = {
    OBJECT(/*model*/ MODEL_CASTLE_KEY_DOOR, /*pos*/ -1100, -1074, 922, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvDoorWarp),
    OBJECT(/*model*/ MODEL_CASTLE_KEY_DOOR, /*pos*/  -946, -1074, 922, /*angle*/ 0, 180, 0, /*behParam*/ 0x00010000, /*beh*/ bhvDoorWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_TO_CASTLE_INSIDE_1_A,  /*destLevel*/ LEVEL_CASTLE,         /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_3_A, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_TO_CASTLE_INSIDE_1_B,  /*destLevel*/ LEVEL_CASTLE,         /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_INSIDE_1_TO_CASTLE_INSIDE_3_B, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_TO_CASTLE_GROUNDS,     /*destLevel*/ LEVEL_CASTLE_GROUNDS, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_GROUNDS_TO_CASTLE_INSIDE_3,    /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_CASTLE_STAR_DOOR_30_STARS, /*pos*/ 307, -1074, 2074, /*angle*/ 0,  90, 0, /*behParam*/ 0x1E << 24, /*beh*/ bhvStarDoor),
    OBJECT(/*model*/ MODEL_CASTLE_STAR_DOOR_30_STARS, /*pos*/ 307, -1074, 1920, /*angle*/ 0, 270, 0, /*behParam*/ 0x1E << 24, /*beh*/ bhvStarDoor),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/ -1690, -1126,  -3942, /*angle*/   0,   0, 0, /*behParam*/ ((PAINTING_ID_CASTLE_LLL << 24) | (WARP_CASTLE_INSIDE_3_PAINTING_LLL << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/ -2611, -1178,  -1075, /*angle*/   0, 180, 0, /*behParam*/ ((PAINTING_ID_CASTLE_SSL << 24) | (WARP_CASTLE_INSIDE_3_PAINTING_SSL << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/  2099, -1485,  -2278, /*angle*/ 270,   0, 0, /*behParam*/ ((PAINTING_ID_CASTLE_HMC << 24) | (WARP_CASTLE_INSIDE_3_PAINTING_HMC << 16)), /*beh*/ bhvPainting),
    OBJECT(/*model*/ MODEL_PAINTING, /*pos*/  3456, -1075,   1587, /*angle*/   0, 270, 0, /*behParam*/ ((PAINTING_ID_CASTLE_DDD << 24) | (WARP_CASTLE_INSIDE_3_PAINTING_DDD << 16)), /*beh*/ bhvPainting),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_PAINTING_LLL,          /*destLevel*/ LEVEL_LLL,    /*destArea*/ 0x01, /*destNode*/ WARP_LLL_1_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_PAINTING_SSL,          /*destLevel*/ LEVEL_SSL,    /*destArea*/ 0x01, /*destNode*/ WARP_SSL_1_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_PAINTING_HMC,          /*destLevel*/ LEVEL_HMC,    /*destArea*/ 0x01, /*destNode*/ WARP_HMC_MAIN_ENTRY,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_PAINTING_DDD,          /*destLevel*/ LEVEL_DDD,    /*destArea*/ 0x01, /*destNode*/ WARP_DDD_1_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  4147, -1280,  1997, /*angle*/ 0,   0, 0, /*behParam*/ ((15 << 24) | (WARP_CASTLE_INSIDE_3_TO_BITFS << 16)), /*beh*/ bhvWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_TO_BITFS,                    /*destLevel*/ LEVEL_BITFS, /*destArea*/ 0x01, /*destNode*/ WARP_BITFS_MAIN_ENTRY, /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1382,  -819, -4150, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_LLL_SUCCESS      << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -2918,  -870,  -875, /*angle*/ 0,   0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_SSL_SUCCESS      << 16), /*beh*/ bhvPaintingStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  2483, -1688, -2662, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_HMC_SUCCESS      << 16), /*beh*/ bhvLaunchStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  2381,  -500,  2011, /*angle*/ 0,  90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_DDD_SUCCESS      << 16), /*beh*/ bhvAirborneStarCollectWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  4147, -1100,  1997, /*angle*/ 0,  90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_BOWSER_2_SUCCESS << 16), /*beh*/ bhvLaunchStarCollectWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_LLL_SUCCESS,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_LLL_SUCCESS,      /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_SSL_SUCCESS,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_SSL_SUCCESS,      /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_HMC_SUCCESS,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_HMC_SUCCESS,      /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_DDD_SUCCESS,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_DDD_SUCCESS,      /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_BOWSER_2_SUCCESS, /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_BOWSER_2_SUCCESS, /*flags*/ WARP_NO_CHECKPOINT),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -1382,  -819, -4150, /*angle*/ 0, 180, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_LLL_DEATH        << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/ -2918,  -870,  -875, /*angle*/ 0,   0, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_SSL_DEATH        << 16), /*beh*/ bhvPaintingDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  2483, -1688, -2662, /*angle*/ 0, 270, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_HMC_DEATH        << 16), /*beh*/ bhvLaunchDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  2381,  -500,  2011, /*angle*/ 0,  90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_DDD_DEATH        << 16), /*beh*/ bhvDeathWarp),
    OBJECT(/*model*/ MODEL_NONE, /*pos*/  4147, -1100,  1997, /*angle*/ 0,  90, 0, /*behParam*/ (WARP_CASTLE_INSIDE_3_FROM_BITFS_DEATH      << 16), /*beh*/ bhvLaunchDeathWarp),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_LLL_DEATH,        /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_LLL_DEATH,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_SSL_DEATH,        /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_SSL_DEATH,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_HMC_DEATH,        /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_HMC_DEATH,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_DDD_DEATH,        /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_DDD_DEATH,   /*flags*/ WARP_NO_CHECKPOINT),
    WARP_NODE(/*id*/ WARP_CASTLE_INSIDE_3_FROM_BITFS_DEATH,      /*destLevel*/ LEVEL_CASTLE, /*destArea*/ 0x03, /*destNode*/ WARP_CASTLE_INSIDE_3_FROM_BITFS_DEATH, /*flags*/ WARP_NO_CHECKPOINT),
    RETURN(),
};

static const LevelScript script_func_local_4[] = {
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -2037,  -818,  -716, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -1648,  -818,  -716, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -1648,  -818,  -101, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -1648,  -818,   512, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -2037,  -818,  -101, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -2969,  -921,   420, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -2037,  -818, -1330, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -3839, -1023, -1422, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/ -1929,  -818, -3615, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_RED_FLAME,  /*pos*/  -834,  -818, -3615, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_BLUE_FLAME, /*pos*/ -3317,  -921,  1229, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_BLUE_FLAME, /*pos*/  -204,  -921,  -624, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    OBJECT(/*model*/ MODEL_BLUE_FLAME, /*pos*/ -2876,  -921,  1229, /*angle*/ 0, 0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvFlame),
    RETURN(),
};

const LevelScript level_castle_inside_entry[] = {
    INIT_LEVEL(),
    LOAD_LEVEL_DATA(castle_inside),
    LOAD_TEXTURE_BIN(inside),
    LOAD_GROUPB(group15),
    ALLOC_LEVEL_POOL(),
    MARIO(/*model*/ MODEL_MARIO, /*behParam*/ 0x00000001, /*beh*/ bhvMario),
    JUMP_LINK(script_func_global_16),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_BOWSER_TRAP,        castle_geo_000F18),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_WATER_LEVEL_PILLAR, castle_geo_001940),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_CLOCK_MINUTE_HAND,  castle_geo_001530),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_CLOCK_HOUR_HAND,    castle_geo_001548),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_CLOCK_PENDULUM,     castle_geo_001518),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_CASTLE_DOOR,        castle_door_geo),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_WOODEN_DOOR,        wooden_door_geo),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_METAL_DOOR,         metal_door_geo),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_CASTLE_DOOR_UNUSED, castle_door_geo),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_WOODEN_DOOR_UNUSED, wooden_door_geo),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_DOOR_0_STARS,       castle_door_0_star_geo),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_DOOR_1_STAR,        castle_door_1_star_geo),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_DOOR_3_STARS,       castle_door_3_stars_geo),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_KEY_DOOR,           key_door_geo),
    // The different sets of star doors all use different model IDs, despite them all loading the same geo layout.
    // It is possible that star doors were originally going to have numbers on them, similar to the other locked doors.
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_STAR_DOOR_30_STARS, castle_geo_000F00),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_STAR_DOOR_8_STARS,  castle_geo_000F00),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_STAR_DOOR_50_STARS, castle_geo_000F00),
    LOAD_MODEL_FROM_GEO(MODEL_CASTLE_STAR_DOOR_70_STARS, castle_geo_000F00),

    AREA(/*index*/ 1, castle_geo_001400),
        OBJECT(/*model*/ MODEL_NONE,       /*pos*/ -5513,  717, -4324, /*angle*/ 0,  45, 0, /*behParam*/ 0x00140000, /*beh*/ bhvCastleFloorTrap),
        OBJECT(/*model*/ MODEL_NONE,       /*pos*/  2477,  307, -2000, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvAquariumBubbles),
        OBJECT(/*model*/ MODEL_NONE,       /*pos*/  2774,  507, -1716, /*angle*/ 0,  90, 0, /*behParam*/ 0x00000000, /*beh*/ bhvTankFishGroup),
        OBJECT(/*model*/ MODEL_NONE,       /*pos*/  3672,  507, -1307, /*angle*/ 0,  45, 0, /*behParam*/ 0x00000000, /*beh*/ bhvTankFishGroup),
        OBJECT(/*model*/ MODEL_NONE,       /*pos*/  3748,  507,   773, /*angle*/ 0, -45, 0, /*behParam*/ 0x00000000, /*beh*/ bhvTankFishGroup),
        OBJECT(/*model*/ MODEL_NONE,       /*pos*/  2778,  507,  1255, /*angle*/ 0, -90, 0, /*behParam*/ 0x00000000, /*beh*/ bhvTankFishGroup),
        OBJECT(/*model*/ MODEL_BOO_CASTLE, /*pos*/ -1000,   50, -3500, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvBooInCastle),
        OBJECT(/*model*/ MODEL_TOAD,       /*pos*/ -1671,    0,  1313, /*angle*/ 0,  83, 0, /*behParam*/ DIALOG_133 << 24, /*beh*/ bhvToadMessage),
        OBJECT(/*model*/ MODEL_TOAD,       /*pos*/  1524,  307,   458, /*angle*/ 0, 110, 0, /*behParam*/ DIALOG_134 << 24, /*beh*/ bhvToadMessage),
        OBJECT(/*model*/ MODEL_TOAD,       /*pos*/   596, -306, -2637, /*angle*/ 0, 152, 0, /*behParam*/ DIALOG_135 << 24, /*beh*/ bhvToadMessage),
        JUMP_LINK(script_func_local_1),
        WARP_NODE(/*id*/ WARP_NODE_DEATH, /*destLevel*/ LEVEL_CASTLE_GROUNDS, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_GROUNDS_DEATH_EXIT, /*flags*/ WARP_NO_CHECKPOINT),
        TERRAIN(/*terrainData*/ inside_castle_seg7_area_1_collision),
        ROOMS(/*surfaceRooms*/ inside_castle_seg7_area_1_rooms),
        MACRO_OBJECTS(/*objList*/ inside_castle_seg7_area_1_macro_objs),
        SET_BACKGROUND_MUSIC(/*settingsPreset*/ SEQ_SETTINGS_PRESET_CASTLE, /*seq*/ SEQ_LEVEL_INSIDE_CASTLE),
        TERRAIN_TYPE(/*terrainType*/ TERRAIN_STONE),
    END_AREA(),

    AREA(/*index*/ 2, castle_geo_001858),
        OBJECT(/*model*/ MODEL_CASTLE_CLOCK_MINUTE_HAND, /*pos*/  -205, 2918, 7222, /*angle*/ 0, 180, 0, /*behParam*/ 0x00000000, /*beh*/ bhvClockMinuteHand),
        OBJECT(/*model*/ MODEL_CASTLE_CLOCK_HOUR_HAND,   /*pos*/  -205, 2918, 7222, /*angle*/ 0, 180, 0, /*behParam*/ 0x00000000, /*beh*/ bhvClockHourHand),
        OBJECT(/*model*/ MODEL_CASTLE_CLOCK_PENDULUM,    /*pos*/  -205, 2611, 7140, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvDecorativePendulum),
        OBJECT(/*model*/ MODEL_LAKITU,                   /*pos*/  4231, 1408, 1601, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvCameraLakitu),
        OBJECT(/*model*/ MODEL_TOAD,                     /*pos*/  -977, 1203, 2569, /*angle*/ 0,   0, 0, /*behParam*/ DIALOG_076 << 24, /*beh*/ bhvToadMessage),
        OBJECT(/*model*/ MODEL_TOAD,                     /*pos*/ -1584, 2253, 7157, /*angle*/ 0, 136, 0, /*behParam*/ DIALOG_083 << 24, /*beh*/ bhvToadMessage),
        OBJECT(/*model*/ MODEL_TOAD,                     /*pos*/   837, 1203, 3020, /*angle*/ 0, 180, 0, /*behParam*/ DIALOG_137 << 24, /*beh*/ bhvToadMessage),
        JUMP_LINK(script_func_local_2),
        WARP_NODE(/*id*/ WARP_NODE_DEATH, /*destLevel*/ LEVEL_CASTLE_GROUNDS, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_GROUNDS_DEATH_EXIT, /*flags*/ WARP_NO_CHECKPOINT),
        TERRAIN(/*terrainData*/ inside_castle_seg7_area_2_collision),
        ROOMS(/*surfaceRooms*/ inside_castle_seg7_area_2_rooms),
        MACRO_OBJECTS(/*objList*/ inside_castle_seg7_area_2_macro_objs),
        INSTANT_WARP(/*index*/ 0, /*destArea*/ 2, /*displace*/ 0, -205, 410),
        SET_BACKGROUND_MUSIC(/*settingsPreset*/ SEQ_SETTINGS_PRESET_CASTLE, /*seq*/ SEQ_LEVEL_INSIDE_CASTLE),
        TERRAIN_TYPE(/*terrainType*/ TERRAIN_STONE),
    END_AREA(),

    AREA(/*index*/ 3, castle_geo_001C10),
        OBJECT(/*model*/ MODEL_CASTLE_WATER_LEVEL_PILLAR, /*pos*/  7066, -1178,  -819, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvWaterLevelPillar),
        OBJECT(/*model*/ MODEL_CASTLE_WATER_LEVEL_PILLAR, /*pos*/  7066, -1178,  -205, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvWaterLevelPillar),
        OBJECT(/*model*/ MODEL_MIPS,                      /*pos*/ -1509, -1177, -1564, /*angle*/ 0,   0, 0, /*behParam*/ 0x00000000, /*beh*/ bhvMips),
        OBJECT(/*model*/ MODEL_TOAD,                      /*pos*/  1787, -1381, -1957, /*angle*/ 0, 126, 0, /*behParam*/ DIALOG_082 << 24, /*beh*/ bhvToadMessage),
        OBJECT(/*model*/ MODEL_TOAD,                      /*pos*/ -4048, -1381, -1334, /*angle*/ 0,  30, 0, /*behParam*/ DIALOG_136 << 24, /*beh*/ bhvToadMessage),
        JUMP_LINK(script_func_local_3),
        JUMP_LINK(script_func_local_4),
        WARP_NODE(/*id*/ WARP_NODE_DEATH, /*destLevel*/ LEVEL_CASTLE_GROUNDS, /*destArea*/ 0x01, /*destNode*/ WARP_CASTLE_GROUNDS_DEATH_EXIT, /*flags*/ WARP_NO_CHECKPOINT),
        TERRAIN(/*terrainData*/ inside_castle_seg7_area_3_collision),
        ROOMS(/*surfaceRooms*/ inside_castle_seg7_area_3_rooms),
        MACRO_OBJECTS(/*objList*/ inside_castle_seg7_area_3_macro_objs),
        SET_BACKGROUND_MUSIC(/*settingsPreset*/ SEQ_SETTINGS_PRESET_CASTLE, /*seq*/ SEQ_LEVEL_INSIDE_CASTLE),
        TERRAIN_TYPE(/*terrainType*/ TERRAIN_STONE),
    END_AREA(),

    FREE_LEVEL_POOL(),
    MARIO_POS(/*area*/ 1, /*yaw*/ 180, /*pos*/ -1023, 0, 1152),
    CALL(/*arg*/ 0, /*func*/ lvl_init_or_update),
    CALL_LOOP(/*arg*/ 1, /*func*/ lvl_init_or_update),
    CLEAR_LEVEL(),
    SLEEP_BEFORE_EXIT(/*frames*/ 1),
    EXIT(),
};
